Rep profile oj
jenesh/jova pull request #21
Opened 2021-02-17 04:42 UTC by ojones311

2021-02-17 23:48 UTC, vonbarown commented on pages/profile/[id].js
> +        <div>
can you add the navbar

2021-02-17 23:51 UTC, vonbarown commented on pages/profile/[id].js
> +        }
You can return the empty the null state directly 
```suggestion
        if(memberInfo){
          return <BasicInfo data={memberInfo}/>
        }
       return <div></div>
```

2021-02-17 23:55 UTC, vonbarown commented on components/Profile/VotingPosition.js
> +    if(data.amendment.length > 0){
you should also check for ``` data.bill.bill_id``` there are voting positions showing up with any id or information

2021-02-17 23:56 UTC, vonbarown commented on components/Profile/VotingPosition.js
> +            </div>
same here, to remove the empty bills
```suggestion
          {data.bill.bill_id && (
          <div className="bill-info">
            <p>{data.date}</p>
            <p>Bill Id: {data.bill.bill_id}</p>
            <h2>Description: {data.description}</h2>
            <h3>Title: {data.bill.title}</h3>
            <p>How Did They Vote: {data.position}</p>
            <p> Vote Result: {data.result}</p>
          </div>
        )}
```

2021-02-17 23:58 UTC, vonbarown commented
run the command ```npm run lint``` in your terminal there are some linter errors

2021-02-18 00:03 UTC, jenesh requested changes

2021-02-18 00:03 UTC, jenesh commented on components/Profile/BasicInfo.js
> +            <p>D.O.B:{" "}{data.date_of_birth}</p>
Write out `Date of Birth`

2021-02-18 00:03 UTC, jenesh commented on components/Profile/BasicInfo.js
> +            <p>Party:{" "}{data.current_party}</p>
Spell out the part instead of R/D

2021-02-18 00:03 UTC, jenesh commented on components/Profile/BasicInfo.js
> +            <p>Website:{" "}<a href={data.url}>{data.url}</a></p>
Open the link in a new tab and on hover make it turn blue w/ underline like a normal a tag.

2021-02-18 00:03 UTC, jenesh commented on components/Profile/BasicInfo.js
> +            <a href={data.rss_url}>{data.rss_url}</a>
The RSS feed should be styled somehow.

2021-02-18 00:03 UTC, jenesh commented on components/Profile/VotingPosition.js
> +                <p>How Did They Vote: {' '}{data.position}</p>
This text doesn't make sense change it to something else.

2021-02-18 01:00 UTC, jenesh approved these changes

2021-02-18 01:00 UTC, merged